### ISSUE TITLE
进度条的控制问题

### ISSUE THREAD

**Issue by DangoSky** [weapon-xx/163music#1]
我发现在播放页面（包括歌词页面）拖动屏幕，都会改变进度条的进度！另外强烈建议开通歌词滚动效果。（我最近也在用vue写一个仿网易云，差不多完成了，这是我的歌词滚动部分的代码：https://github.com/DangoSky/cloud-music/blob/master/src/components/base/lyric.vue，一起交流学习啊）

**Comment by weapon-xx** [comment]
> 我发现在播放页面（包括歌词页面）拖动屏幕，都会改变进度条的进度！另外强烈建议开通歌词滚动效果。（我最近也在用vue写一个仿网易云，差不多完成了，这是我的歌词滚动部分的代码：[https://github.com/DangoSky/cloud-music/blob/master/src/components/base/lyric.vue，一起交流学习啊）](https://github.com/DangoSky/cloud-music/blob/master/src/components/base/lyric.vue%EF%BC%8C%E4%B8%80%E8%B5%B7%E4%BA%A4%E6%B5%81%E5%AD%A6%E4%B9%A0%E5%95%8A%EF%BC%89)

是真机测试的吗？
歌词滚动其实一直想做的，后续会加上去 😁

**Comment by weapon-xx** [comment]
35bce6e5e49568e79f37b414a92161388e4fe00a
