### ISSUE TITLE
歌曲封面图片的显示问题

### ISSUE THREAD

**Issue by DangoSky** [weapon-xx/163music#2]
![_20190225170716](https://user-images.githubusercontent.com/42209399/53326219-f9d89180-391f-11e9-8526-5aaa42ab3d90.png)
（坐标：那些喜欢到循环播放的歌 歌单里第三首）

**Comment by weapon-xx** [comment]
> ![_20190225170716](https://user-images.githubusercontent.com/42209399/53326219-f9d89180-391f-11e9-8526-5aaa42ab3d90.png)
> （坐标：那些喜欢到循环播放的歌 歌单里第三首）

get ✅

**Comment by weapon-xx** [comment]
get ✅

**Comment by weapon-xx** [comment]
60812cc84388e0261fd138b9153f3406b5cb7221
