### ISSUE TITLE
关于点击歌曲后自动播放的问题

### ISSUE THREAD

**Issue by DangoSky** [weapon-xx/163music#3]
建议改为点击歌曲后可以自动播放歌曲，这样用户体验比较好。可以使用
```
    setTimeout(() => {
        this.$refs.player.play();
    },0)
```
来代替被禁止的autoplay功能（我就是这么解决的）。

**Comment by weapon-xx** [comment]
点击播放后是会播放音乐的；
如果直接调用 play() 是会提示错误的

**Comment by weapon-xx** [comment]
> 建议改为点击歌曲后可以自动播放歌曲，这样用户体验比较好。可以使用
> 
> ```
>     setTimeout(() => {
>         this.$refs.player.play();
>     },0)
> ```
> 来代替被禁止的autoplay功能（我就是这么解决的）。

点击播放后是会播放音乐的；
如果直接调用 play() 是会提示错误的

**Comment by DangoSky** [comment]
我的意思是从歌单列表点击歌曲，进入到播放页面后可以自动播放歌曲。下午那会我测试了几次都是从歌单列表点击歌曲后还得在播放页面按播放按钮才可以播放

**Comment by weapon-xx** [comment]
> 我的意思是从歌单列表点击歌曲，进入到播放页面后可以自动播放歌曲。下午那会我测试了几次都是从歌单列表点击歌曲后还得在播放页面按播放按钮才可以播放

明白了；
因为现在把自动播放的功能去掉了，我晚点尝试下这个方法

**Comment by weapon-xx** [comment]
0c3ed9ef3033aab2cec4571465724d9f4b921f74
